language: python
dist: xenial
cache: pip
install: travis_retry pip install -U tox
script: tox
jobs:
  include:
  - { python: '3.6', env: TOXENV=lint }
  - { python: '3.6', env: TOXENV=py36 }
  - { python: '3.7', env: TOXENV=py37 }
