"""add index

Revision ID: 8a7f2a4fd8c2
Revises: 1cea0a2cc58f
Create Date: 2019-05-12 23:18:42.212381

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "8a7f2a4fd8c2"
down_revision = "1cea0a2cc58f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_widgets_name"), "widgets", ["name"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_widgets_name"), table_name="widgets")
    # ### end Alembic commands ###
